// src/lib/quotationCatalog.ts

export interface CatalogItem {
  id: string;
  name: string;
  category: 'professional' | 'camera' | 'audio' | 'lighting' | 'data' | 'logistics' | 'postproduction' | 'extra';
  sectionName: string;
  defaultRate: number; // in KES
  defaultUnit: 'day' | 'item' | 'output' | 'set';
  defaultNotes?: string;
}

export const QUOTATION_CATALOG: CatalogItem[] = [
  // A. Professional Fees (Core)
  {
    id: 'prof-photo',
    name: 'Photographers',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 25000,
    defaultUnit: 'day',
    defaultNotes: 'Photographers professional fee',
  },
  {
    id: 'prof-dop',
    name: 'Videographer (Director & DOP)',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 45000,
    defaultUnit: 'day',
    defaultNotes: 'Video DOP',
  },
  {
    id: 'prof-ad',
    name: 'Videographer (AD)',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 25000,
    defaultUnit: 'day',
    defaultNotes: 'Podcast Video AD',
  },
  {
    id: 'prof-drone-pilot',
    name: 'Drone Pilot & Aerial Cinematographer',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 30000,
    defaultUnit: 'day',
    defaultNotes: 'Licensed aerial operator & spotter',
  },
  {
    id: 'prof-sound-eng',
    name: 'Sound Recordist & Boom Operator',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 20000,
    defaultUnit: 'day',
    defaultNotes: 'Dedicated location multi-track audio',
  },
  {
    id: 'prof-gaffer',
    name: 'Gaffer & Grip Key',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 18000,
    defaultUnit: 'day',
    defaultNotes: 'Lighting setup and power management',
  },
  {
    id: 'prof-pa',
    name: 'Production Assistant (PA)',
    category: 'professional',
    sectionName: 'A. Professional Fees (Core)',
    defaultRate: 10000,
    defaultUnit: 'day',
    defaultNotes: 'On-set logistics and equipment coordination',
  },

  // Camera Packages
  {
    id: 'cam-sony-a7s3',
    name: 'Main Video Cameras (Sony A7sIII)',
    category: 'camera',
    sectionName: 'Camera Package (Podcast Video)',
    defaultRate: 8000,
    defaultUnit: 'day',
    defaultNotes: 'Primary 4K 10-bit cinema camera',
  },
  {
    id: 'cam-lenses-zoom',
    name: 'Lenses (16-35mm, 2- 50 mm)',
    category: 'camera',
    sectionName: 'Camera Package (Podcast Video)',
    defaultRate: 3000,
    defaultUnit: 'day',
    defaultNotes: 'Fast GM primes and zoom lenses',
  },
  {
    id: 'cam-tripods',
    name: 'Tripods (heavy duty)',
    category: 'camera',
    sectionName: 'Camera Package (Podcast Video)',
    defaultRate: 1000,
    defaultUnit: 'day',
    defaultNotes: 'Fluid head support equipment',
  },
  {
    id: 'cam-sony-a74',
    name: 'Main Video Cameras (Sony A7 IV)',
    category: 'camera',
    sectionName: 'Camera Package (Coverage Video)',
    defaultRate: 8000,
    defaultUnit: 'day',
    defaultNotes: 'Primary camera',
  },
  {
    id: 'cam-lenses-2470',
    name: 'Lenses (24-70 mm)',
    category: 'camera',
    sectionName: 'Camera Package (Coverage Video)',
    defaultRate: 3000,
    defaultUnit: 'day',
    defaultNotes: 'Mid-range zoom lens',
  },
  {
    id: 'cam-gimbal',
    name: 'DJI RS5 / RS3 Pro Gimbal',
    category: 'camera',
    sectionName: 'Camera Package (Coverage Video)',
    defaultRate: 4000,
    defaultUnit: 'day',
    defaultNotes: 'Stabilization & support equipment',
  },
  {
    id: 'cam-photo-a74',
    name: 'Main Photo Cameras (Sony A74 / A7R V)',
    category: 'camera',
    sectionName: 'Camera Package (Photo)',
    defaultRate: 8000,
    defaultUnit: 'day',
    defaultNotes: 'Primary high-res stills body',
  },
  {
    id: 'cam-photo-telephoto',
    name: 'Lenses (24-70mm, 70-200 mm)',
    category: 'camera',
    sectionName: 'Camera Package (Photo)',
    defaultRate: 3000,
    defaultUnit: 'day',
    defaultNotes: 'Telephoto & event coverage glass',
  },
  {
    id: 'cam-fx6',
    name: 'Sony FX6 Cinema Camera Package',
    category: 'camera',
    sectionName: 'Camera Package (Cinema)',
    defaultRate: 15000,
    defaultUnit: 'day',
    defaultNotes: 'Full-frame cinema line system with monitor & V-Mounts',
  },

  // Audio Package
  {
    id: 'aud-lav-wireless',
    name: 'Wireless Lavalier Mic (Dual set - DJI/Rode)',
    category: 'audio',
    sectionName: 'Audio Package',
    defaultRate: 2000,
    defaultUnit: 'day',
    defaultNotes: 'Primary audio',
  },
  {
    id: 'aud-shotgun',
    name: 'Shotgun Mic + Boom',
    category: 'audio',
    sectionName: 'Audio Package',
    defaultRate: 1500,
    defaultUnit: 'day',
    defaultNotes: 'Backup / environmental capture',
  },
  {
    id: 'aud-recorder',
    name: 'Audio Recorder (Zoom H5/H6)',
    category: 'audio',
    sectionName: 'Audio Package',
    defaultRate: 1000,
    defaultUnit: 'day',
    defaultNotes: 'Podcast backup recording',
  },
  {
    id: 'aud-sennheiser',
    name: 'Sennheiser EW-DP Broadcast Wireless Mic',
    category: 'audio',
    sectionName: 'Audio Package',
    defaultRate: 2500,
    defaultUnit: 'day',
    defaultNotes: 'UHF broadcast clarity',
  },

  // Lighting Package
  {
    id: 'light-amaran-400d',
    name: 'Amaran 400D / 300C (bicolor)',
    category: 'lighting',
    sectionName: 'Lighting Package',
    defaultRate: 4000,
    defaultUnit: 'day',
    defaultNotes: 'Portable high-output lighting',
  },
  {
    id: 'light-godox-v1',
    name: 'Godox V1 Speedlights',
    category: 'lighting',
    sectionName: 'Lighting Package',
    defaultRate: 3000,
    defaultUnit: 'day',
    defaultNotes: 'Flash Lighting',
  },
  {
    id: 'light-stands',
    name: 'Light stands & modifiers (Softboxes/C-stands)',
    category: 'lighting',
    sectionName: 'Lighting Package',
    defaultRate: 500,
    defaultUnit: 'day',
    defaultNotes: 'Grip & diffusion setup',
  },
  {
    id: 'light-aputure-600',
    name: 'Aputure LS 600d Pro Daylight',
    category: 'lighting',
    sectionName: 'Lighting Package',
    defaultRate: 8000,
    defaultUnit: 'day',
    defaultNotes: 'Key cinematic punch light with Lantern / Dome',
  },
  {
    id: 'light-tubes',
    name: 'Nanlite Pavotube II RGB Tubes (Kit of 4)',
    category: 'lighting',
    sectionName: 'Lighting Package',
    defaultRate: 4000,
    defaultUnit: 'day',
    defaultNotes: 'Atmospheric and accent RGB lighting',
  },

  // Data & Storage
  {
    id: 'data-hdd',
    name: 'HDD / NVMe Drives (1 TB) + backup storage',
    category: 'data',
    sectionName: 'Data & Storage',
    defaultRate: 13000,
    defaultUnit: 'item',
    defaultNotes: 'Primary and backup media',
  },
  {
    id: 'data-dit',
    name: 'DIT (Digital Intermediate Tech & Ingest)',
    category: 'data',
    sectionName: 'Data & Storage',
    defaultRate: 5000,
    defaultUnit: 'day',
    defaultNotes: 'Offload, verification, backup handling',
  },
  {
    id: 'data-cloud',
    name: 'High-Speed Cloud Delivery & 1-Year Archive',
    category: 'data',
    sectionName: 'Data & Storage',
    defaultRate: 4000,
    defaultUnit: 'item',
    defaultNotes: 'Secure client portal hosting',
  },

  // Travel & Logistics
  {
    id: 'logistics-ground',
    name: 'Ground + Equipment transport',
    category: 'logistics',
    sectionName: 'C. Travel & Logistics',
    defaultRate: 2000,
    defaultUnit: 'day',
    defaultNotes: 'Fuel, taxis, local movement',
  },
  {
    id: 'logistics-out-of-town',
    name: 'Out of Town Crew Travel & Per Diem',
    category: 'logistics',
    sectionName: 'C. Travel & Logistics',
    defaultRate: 15000,
    defaultUnit: 'day',
    defaultNotes: 'Accommodations, regional travel, per diem',
  },

  // Postproduction
  {
    id: 'post-photo',
    name: 'Photo Postproduction',
    category: 'postproduction',
    sectionName: 'Postproduction (Per output billing)',
    defaultRate: 10000,
    defaultUnit: 'output',
    defaultNotes: 'Batch Processing (Same day Delivery)',
  },
  {
    id: 'post-video',
    name: 'Video Postproduction',
    category: 'postproduction',
    sectionName: 'Postproduction (Per output billing)',
    defaultRate: 7000,
    defaultUnit: 'output',
    defaultNotes: 'Event Coverage + Highlight video + Podcast Output',
  },
  {
    id: 'post-color-grading',
    name: 'Cinematic Color Grading & Sound Master',
    category: 'postproduction',
    sectionName: 'Postproduction (Per output billing)',
    defaultRate: 15000,
    defaultUnit: 'output',
    defaultNotes: 'DaVinci Resolve color grading & sound mix',
  },
  {
    id: 'post-reels',
    name: 'Social Media Cutdowns (Reels / TikTok / Shorts)',
    category: 'postproduction',
    sectionName: 'Postproduction (Per output billing)',
    defaultRate: 4000,
    defaultUnit: 'output',
    defaultNotes: 'Vertical 9:16 optimized cuts with dynamic captions',
  },
];
